version: '3.0'
services:
  server:
    image: spike-server:0.0.1
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: always
        delay: 15s
      resources:
        limits:
          cpus: "2"
          memory: 100M
        reservations: 
          cpus: "0.2"
          memory: 50M
  worker:
    image: spike-worker:0.0.1
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          cpus: "2"
          memory: "100M"
        reservations:
          cpus: "0.5"
          memory: 50M