version: '3.0'
services:
  backend:
    image: spike:0.0.1 
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
        reservations: 
          cpus: "0.2"
          memory: 50M