version: '3.0'
name: spike-microservices
services:
  server:
    image: spike-server:0.0.1
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: always
        delay: 15s
      resources:
        limits:
          cpus: "2"
          memory: 100M
        reservations: 
          cpus: "0.2"
          memory: 50M
  worker:
    image: spike-worker:0.0.1
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          cpus: "2"
          memory: "100M"
        reservations:
          cpus: "0.5"
          memory: 50M
  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus
        target: /etc/prometheus/


    deploy:
      replicas: 1
      resources:
        limits:
          memory: 50M
          cpus: "0.4"
        reservations:
          memory: "40M"
          cpus: "0.2"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    # TODO: permissions
    # volumes:
    #   - ./data/grafana:/etc/grafana
    #   - ./data/grafana:/var/log/grafana
    #   - ./data/grafana:/var/lib/grafana

    ports: 
      - "3000:3000"
    deploy:
      restart_policy: 
        condition: always
      resources:
        limits:
          memory: "60M"
          cpus: "0.2"
        reservations:
          memory: "45M"
          cpus: "0.1"

    
configs:
  prometheus:
    file: ./prometheus


